/* Albania Now — The Eagle's Flight: engine + levels.
   Loaded by eagle.html AND executed by tools/test_eagle.js — every level's
   par solution is machine-verified through this exact engine.

   World: 9x7 grid. Directions 0=E,1=S,2=W,3=N. Commands: 'F' fly one cell,
   'L'/'R' turn, '1' call F1 (main only; F1 is a flat sequence).
   Levels are authored as a start pose + a par SOLUTION; the star layout is
   generated by running that solution and dropping stars on chosen steps —
   solvability is by construction, and the test re-proves it. */

var EAGLE_W = 9, EAGLE_H = 7, EAGLE_MAXSTEPS = 200;

var EAGLE_LEVELS = [
 {name:'First flight',      start:[1,3,0], sol:{main:'FFF',      f1:''},     starSteps:[1,2,3],       hint:'fluturo moves one cell.'},
 {name:'The turn',          start:[1,2,0], sol:{main:'FFRFF',    f1:''},     starSteps:[2,4,5],       hint:'djathtas turns right — turning is not moving.'},
 {name:'Both wings',        start:[1,5,0], sol:{main:'FFLFFRFF', f1:''},     starSteps:[2,4,5,7],     hint:'majtas turns left.'},
 {name:'The hook',          start:[1,1,0], sol:{main:'FFFRFFRFF',f1:''},     starSteps:[3,5,6,8],     hint:'Two rights make a U.'},
 {name:'Teach it a word',   start:[1,1,0], sol:{main:'1R1R1',    f1:'FF'},   starSteps:[2,5,8],       hint:'F1 is a word YOU define. Put FF inside it, then say the word.'},
 {name:'Say it again',      start:[1,1,0], sol:{main:'1R1L1R1',  f1:'FF'},   starSteps:[2,5,8,11],    hint:'One definition, four uses — that is the whole trick.'},
 {name:'The square',        start:[2,1,0], sol:{main:'1111',     f1:'FFR'},  starSteps:[2,5,8,11],    hint:'Put the turn INSIDE the word and the square draws itself.'},
 {name:'Widdershins',       start:[6,1,2], sol:{main:'1111',     f1:'FFL'},  starSteps:[2,5,8,11],    hint:'Same square, other wing.'},
 {name:'The staircase',     start:[1,2,0], sol:{main:'111',      f1:'FRFL'}, starSteps:[1,3,5,7,9,11],hint:'A step is fly, turn, fly, turn — name it once.'},
 {name:'The long stair',    start:[1,6,0], sol:{main:'1111',     f1:'FLFR'}, starSteps:[2,4,6,8],     hint:'Climbing this time. Which turn comes first?'},
 {name:'The battlement',    start:[1,1,0], sol:{main:'111',      f1:'FRFLF'},starSteps:[2,4,7,9,12,14],hint:'East, dip south, east again — five moves, one word.'},
 {name:'The serpent',       start:[1,0,0], sol:{main:'111',      f1:'FFRFFL'},starSteps:[2,5,8,11,14,17],hint:'Two east, two south — one word, said three times.'},
 {name:'Tight slots',       start:[1,1,0], sol:{main:'111',      f1:'FFRF'}, starSteps:[2,3,6,7,10,11],hint:'Only three slots in main. The word must carry everything.'},
 {name:'The grand square',  start:[1,1,0], sol:{main:'1111',     f1:'FFFR'}, starSteps:[1,3,5,7,9,11],hint:'Bigger square, same idea. Count before you fly.'},
 {name:'The lightning',     start:[1,0,0], sol:{main:'11L1',     f1:'FFRFFL'},starSteps:[2,5,8,11,14,18],hint:'The serpent again — then a correction, and higher ground.'},
 {name:'The eagle’s path',  start:[1,3,0], sol:{main:'1R11L1',   f1:'FFL'},  starSteps:[1,4,7,10,13], hint:'Everything at once. Fly well.'}
];

function eagleRun(level, main, f1){
  // returns {steps:[{x,y,dir,collect}...], ok, reason, visited}
  var x=level.start[0], y=level.start[1], d=level.start[2];
  var steps=[{x:x,y:y,dir:d}];
  var prog=[];
  for(var i=0;i<main.length;i++){
    var c=main[i];
    if(c==='1'){for(var j=0;j<f1.length;j++)prog.push(f1[j]);}
    else prog.push(c);
  }
  if(prog.length>EAGLE_MAXSTEPS)return {steps:steps,ok:false,reason:'too long'};
  var DX=[1,0,-1,0],DY=[0,1,0,-1];
  for(var k=0;k<prog.length;k++){
    var op=prog[k];
    if(op==='L')d=(d+3)%4;
    else if(op==='R')d=(d+1)%4;
    else if(op==='F'){
      x+=DX[d];y+=DY[d];
      if(x<0||x>=EAGLE_W||y<0||y>=EAGLE_H)
        return {steps:steps,ok:false,reason:'off the map'};
    }
    steps.push({x:x,y:y,dir:d});
  }
  return {steps:steps,ok:true,reason:''};
}

function eagleStars(level){
  // star layout by construction: run the par solution, drop stars at starSteps
  var r=eagleRun(level, level.sol.main, level.sol.f1);
  if(!r.ok)return null;
  var stars=[];
  var seen={};
  for(var i=0;i<level.starSteps.length;i++){
    var s=r.steps[level.starSteps[i]];
    if(!s)return null;
    var key=s.x+','+s.y;
    if(seen[key])continue;
    seen[key]=1;
    stars.push([s.x,s.y]);
  }
  return stars;
}

function eagleJudge(level, main, f1){
  // run a player program; return {ok, collected, total, used, par, stars}
  var starList=eagleStars(level);
  var r=eagleRun(level, main, f1);
  var got={};
  for(var i=0;i<r.steps.length;i++){
    var s=r.steps[i];
    got[s.x+','+s.y]=1;
  }
  var collected=0;
  for(var j=0;j<starList.length;j++)
    if(got[starList[j][0]+','+starList[j][1]])collected++;
  var used=main.length+f1.length;
  var par=level.sol.main.length+level.sol.f1.length;
  var win=r.ok&&collected===starList.length;
  var stars=win?(used<=par?3:(used<=par+3?2:1)):0;
  return {ok:win,crashed:!r.ok,reason:r.reason,collected:collected,
          total:starList.length,used:used,par:par,stars:stars,run:r};
}

if(typeof module!=='undefined')module.exports={
  LEVELS:EAGLE_LEVELS,run:eagleRun,stars:eagleStars,judge:eagleJudge,
  W:EAGLE_W,H:EAGLE_H};
